<?php

// Genero: ProgramasProgramacion.com
echo "<!DOCTYPE html>\n";
echo "\n";
echo "<html lang=\"es-co\" xmlns=\"http://www.w3.org/1999/xhtml\">\n";
echo "<head>\n";
echo "    <meta charset=\"utf-8\" />\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n";
echo "    <title>Pagina principal</title>\n";
echo "    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">\n";
echo "</head>\n";
echo "<body background=\"Capturas/fondo.png\">\n";
echo "    <div class=\"container\">\n";
echo "        <div class=\"row\" style=\"height:100px\">\n";
echo "\n";
echo "        </div>\n";
echo "        <div class=\"row\" style=\"height:50px\">\n";
echo "\n";
echo "        </div>\n";
echo "        <div class=\"row\">\n";
echo "            <div class=\"col-4\">\n";
echo "                <div class=\"card\" style=\"width: 18rem;\">\n";
echo "                    <img src=\"Capturas/Breakout.png\" class=\"card-img-top\" alt=\"...\" width=\"100\" height=\"100\">\n";
echo "                    <div class=\"card-body\">\n";
echo "                        <h5 class=\"card-title\">Breakout</h5>\n";
echo "                        <a href=\"juego.php?id=Breakout\" class=\"btn btn-primary\" id=\"breakout\" onclick=\"guardar('Breakout')\">Jugar</a>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "            \n";
echo "            <div class=\"col-4\">\n";
echo "                <div class=\"card\" style=\"width: 18rem;\">\n";
echo "                    <img src=\"Capturas/Capture.png\" class=\"card-img-top\" alt=\"...\" width=\"100\" height=\"100\">\n";
echo "                    <div class=\"card-body\">\n";
echo "                        <h5 class=\"card-title\">Capture the princess</h5>\n";
echo "                        <a href=\"juego.php?id=Capture\" class=\"btn btn-primary\" id=\"Capture\" onclick=\"guardar('Capture')\">Jugar</a>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "            \n";
echo "            <div class=\"col-4\">\n";
echo "                <div class=\"card\" style=\"width: 18rem;\">\n";
echo "                    <img src=\"Capturas/FlappyMario.PNG\" class=\"card-img-top\" alt=\"...\" width=\"100\" height=\"100\">\n";
echo "                    <div class=\"card-body\">\n";
echo "                        <h5 class=\"card-title\">Flappy Mario</h5>\n";
echo "                        <a href=\"juego.php?id=FlappyMario\" class=\"btn btn-primary\" id=\"flappyMario\" onclick=\"guardar('FlappyMario')\">Jugar</a>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "            \n";
echo "        </div>\n";
echo "        <div class=\"row\" style=\"height:50px\">\n";
echo "\n";
echo "        </div>\n";
echo "        <div class=\"row\">\n";
echo "            \n";
echo "            <div class=\"col-4\">\n";
echo "            </div>\n";
echo "            <div class=\"col-4\">\n";
echo "                <center>\n";
echo "                <div class=\"card\" style=\"width: 18rem;\">\n";
echo "                    <img src=\"Capturas/Pacman.png\" class=\"card-img-top\" alt=\"...\" width=\"100\" height=\"100\">\n";
echo "                    <div class=\"card-body\">\n";
echo "                        <h5 class=\"card-title\">Pacman</h5>\n";
echo "                        <a href=\"juego.php?id=Pacman\" class=\"btn btn-primary\" id=\"Pacman\" onclick=\"guardar('Pacman')\">Jugar</a>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "                </center>\n";
echo "            </div>\n";
echo "            \n";
echo "            <div class=\"col-4\">\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "\n";
echo "    <script src=\"js/jquery-3.3.1.slim.min.js\"></script>\n";
echo "    <script src=\"js/popper.min.js\"></script>\n";
echo "    <script src=\"js/bootstrap.min.js\"></script>\n";
echo "</body>\n";
echo "</html>\n";

?>